package ru.telnov.labs.translationmethods.parsergenerator.utils;

import ru.telnov.labs.translationmethods.parsergenerator.tokens.Rule;
import ru.telnov.labs.translationmethods.parsergenerator.tokens.Terminal;

import java.util.Collections;
import java.util.Set;

public final class Constants {

    private Constants() {
    }

    public static final String[] TABS = {
            "",
            "    ",
            "        ",
            "            ",
            "                "
    };

    public static String FILE_HEADER = "// This class was generated by Telnov's parser-generator";

    public static final String EPSILON = "\u03B5";
    public static final Terminal EPSILON_TERMINAL = new Terminal();
    public static final Set<Terminal> EPSILON_SET = Collections.singleton(EPSILON_TERMINAL);
    public static final Rule EPSILON_RULE = new Rule(new Terminal("EMPTY", EPSILON));


    public static final String END_LINE = "$";
    public static final Terminal END_LINE_TERMINAL = new Terminal("ENDLINE", END_LINE);


    public static final String GEN_PACKAGE_NAME = "gen_parser";
    public static final String ENUM_TYPE_CLASS = "TypeToken";
    public static final String TREE_NODE_CLASS = "Node";
    public static final String LEXER_TOKEN_CLASS = "Token";
}
