expr returns (Integer outVal)
    : total
        { Integer v = totalNode.getValue(); }
        { outVal = v == null ? 0 : v;       }
      expr1<outVal>
        { if (expr1Node.getValue() != null) }
        {   outVal = expr1Node.getValue();  }
    ;

expr1 (Integer inVal) returns (Integer outVal)
    : opPlusMinus
        { String op = opPlusMinusNode.getValue();       }
      total
        { Integer v = totalNode.getValue();             }
        { if (op.equals("+")) outVal = inVal + v;       }
        { else if (op.equals("-")) outVal = inVal - v;  }
        { else outVal = inVal;                          }
      expr1<outVal>
        { if (expr1Node.getValue() != null)             }
        {   outVal = expr1Node.getValue();              }
    |
    ;

opPlusMinus returns (String s)
    : PLUS  { s = "+";  }
    | MINUS { s = "-";  }
    ;

total returns (Integer outVal)
    : mul
        { outVal = mulNode.getValue();          }
      total1<outVal>
        { if (total1Node.getValue() != null)    }
        {   outVal = total1Node.getValue();     }
    ;

total1 (Integer inVal) returns (Integer outVal)
    : opMulDiv
        { String op = opMulDivNode.getValue();          }
      mul
        { Integer v = mulNode.getValue();               }
        { if (op.equals("*")) outVal = inVal * v;       }
        { else if (op.equals("/")) outVal = inVal / v;  }
        { else outVal = inVal;                          }
      total1<outVal>
        { if (total1Node.getValue() != null)            }
        {   outVal = total1Node.getValue();             }
    |
    ;

opMulDiv returns (String s)
    : MUL   { s = "*";  }
    | DIV   { s = "/";  }
    ;

mul returns (Integer outVal)
    : LPAREN expr RPAREN
        { outVal = exprNode.getValue();                 }
    | VALUE
        { outVal = Integer.valueOf(getLastTerminal());  }
    | opPlusMinus
        { String unOp = opPlusMinusNode.getValue();       }
      VALUE
        { String v = getLastTerminal();                 }
        { outVal = Integer.valueOf(unOp + v);           }
    ;
